#!/bin/sh

cd ~

export _JAVA_AWT_WM_NONREPARENTING=1
export WLR_NO_HARDWARE_CURSORS=1
export XDG_SESSION_TYPE=wayland
export GTK_THEME=Catppuccin-Mocha-Standard-Teal-Dark
export GTKTHEME=Catppuccin-Mocha-Standard-Teal-Dark
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_STYLE_OVERRIDE=kvantum

EDP=$(cat /sys/class/drm/card1-eDP-1/status) # Internal laptop display

if [ "$EDP" = 'connected' ]; then
    export LAPTOP=1
    export XCURSOR_SIZE=24
else
    export LAPTOP=0
    export XCURSOR_SIZE=48
fi

exec Hyprland
