version: "3.9"

services:
  mcp-docker:
    image: mcp-server-docker:latest
    build:
      context: "{{HOME}}/.local/src/mcp-server-docker"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # no ports: uses stdio

